name: prepull-windows-container-image

on:
  workflow_dispatch:
    inputs:
      containerImage:
        description: 'Image name and tag that is used for docker pull'
        required: true
        default: 'mcr.microsoft.com/windows/servercore:1809'
      sshKeyName:
        description: 'ssh key name associated with WMCO'
        required: true
        default: 'cloud-private-key'
      s3_storage:
        description: 'AWS S3 storage bucket name (i.e. ocp-s3-storage)'
        required: true
      clusterConfigName:
        description: 'Folder name of cluster config in S3 to pull down for auth.  Example: ocp-[run_number]'
        required: true

jobs:
  prepull-windows-container-image:
    runs-on: macos-latest
    env:
      temp_dir: "temp-${{ github.run_number }}"

    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "${{ github.event.inputs.region }}"

      - name: Get cluster metadata files from S3
        shell: bash
        run: |
          mkdir -p ./${{ env.temp_dir }}
          echo "Downloading ${{ github.event.inputs.clusterConfigName }} metadata files from S3..."
          aws s3 sync s3://${{ github.event.inputs.s3_storage }}/${{ github.event.inputs.clusterConfigName }} ./${{ env.temp_dir }} --region ${{ github.event.inputs.region }}

      - name: Pre-pull Windows container image job
        shell: bash
        run: |
          export KUBECONFIG=$(pwd)/${{ env.temp_dir }}/auth/kubeconfig
          oc login -u ${{ secrets.OC_USER }} -p ${{ secrets.OC_PASSWORD }}
          export windowsIP=$(oc get node -l kubernetes.io/os=windows,node-role.kubernetes.io/worker -o json | jq -r '.items[0].status.addresses[0].address')
          export containerImage=${{ github.event.inputs.containerImage }}
          export sshkeySecretName='cloud-private-key'
          export id=${{ github.run_number }}
          envsubst < ./crd/prepull-image-template.yaml >> ./${{ env.temp_dir }}/prepull-image.yaml
          oc project openshift-windows-machine-config-operator
          oc create -f ./${{ env.temp_dir }}/prepull-image.yaml
          oc wait --for=condition=complete --timeout=900s job/pre-pull-windows-image-${{ github.run_number }}
